#!/bin/bash
if [ -z "${PROJECTS_PATH}" ]; then
    export PROJECTS_PATH="~/Projects"
fi

function project() {

    if [ "${1}" != "" ]; then
        PROJECTS_PATH=$(echo ${PROJECTS_PATH} | sed 's/\;.*//')
        eval cd "${PROJECTS_PATH}/${1}/"
	clear
        git status -sb
    fi

}

# Bash completion for `project`
function _project() {
    local cur opts abs absesc
    COMPREPLY=()
    PROJECTS_PATH=$(echo ${PROJECTS_PATH} | sed 's/\;.*//')
    abs=$(eval cd "${PROJECTS_PATH}"; pwd)
    absesc=$(echo ${abs} | sed 's/[][\.*^$/]/\\&/g')
    cur="${COMP_WORDS[COMP_CWORD]}"
    opts=$(eval ls -d "${abs}/*" | sed "s/^${absesc}\///")

    COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
    return 0
}
complete -F _project project
