#!/bin/bash
# Quick way to start/stop headless servers in VirtualBox
headless() {
    startstop=$1
    servername=$2   

    if [ "$servername" == "" -a "$startstop" != "start" -a "$startstop" != "stop" ]; then
        servername=$startstop
        if [ `VBoxManage list runningvms | grep "$servername" | wc -l` -eq 0 ]; then
            startstop="start"
        else
            startstop="stop"
        fi

    fi

    if [ "$servername" == "" ] || [ `VboxManage list vms | grep "\"$servername\"" | wc -l` -eq 0 ]; then
        echo "Please provide a VM name. Possible values are:"
        VBoxManage list vms | sed -e 's/{.*$//' | grep "[^\"]"
        return 1
    fi

    if [ "$startstop" = "start" ]; then
        command="startvm --type headless ${servername}"
    else
        command="controlvm ${servername} savestate"
    fi
    VBoxManage ${command} &
}

# Bash completion for `headless`
function _headless() {
    local cur opts prev cmd
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    
    case "${COMP_CWORD}" in
        1)
            opts="`VBoxManage list vms | sed -e 's/{.*$//' | sed 's/"//g'`"
            opts="${opts} start stop"
            COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
            return 0
            ;;
        *)
            if [ "${prev}" == "stop" ]; then
                cmd="runningvms"
            else
                cmd="vms"
            fi

            opts="`VBoxManage list ${cmd} | sed -e 's/{.*$//' | sed 's/"//g'`"
            COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
            return 0
            ;;
    esac

    return 0
}
complete -F _headless headless