#!/bin/bash
if [ -z "${PROJECTS_PATH}" ]; then
    export PROJECTS_PATH='~/Projects'
fi

function project() {

    if [ "${1}" != "" ]; then
        cd ${PROJECTS_PATH}/${1}/
	clear
        git status -sb
    fi

}

# Bash completion for `project`
function _project() {
    local cur opts abs
    COMPREPLY=()
    abs=$(cd ${PROJECTS_PATH}; pwd | sed 's/[][\.*^$/]/\\&/g')
    cur="${COMP_WORDS[COMP_CWORD]}"
    opts=$(ls -d ${PROJECTS_PATH}/*/ | sed "s/^${abs}\///")

    COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
    return 0
}
complete -F _project project
