#!/bin/bash
briefcase() {
    if [ $1 = "wanker" ]; then
        command briefcase git stash && briefcase git pull && briefcase git stash pop && briefcase generate && briefcase sync;
    else
        command briefcase "$@";
    fi;
}
