import = ["/Users/keith/.cache/wal/colors-alacritty.yml"]

[cursor]
style = "Block"
thickness = 0.1
unfocused_hollow = true

[font]
size = 13

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
#family = "Monaspace Neon"
family = "MonaspiceNe NFP"
style = "Light"

[[keyboard.bindings]]
chars = "\bK"
key = "K"
mods = "Super"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Super|Shift"

## Tmux

# Super+T / Control+T -> Create Window (Ctrl+b c)
[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Super"
[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Control"

# Super+Shift+} / Control+Tab -> Next Window (Ctrl+b n)
[[keyboard.bindings]]
chars = "\u0002n"
key = "}"
mods = "Super|Shift"
[[keyboard.bindings]]
chars = "\u0002n"
key = "Tab"
mods = "Control"

# Super+Shift+{ / Control+Shift+Tab -> Previous Window (Ctrl+b p)
[[keyboard.bindings]]
chars = "\u0002p"
key = "{"
mods = "Super|Shift"
[[keyboard.bindings]]
chars = "\u0002p"
key = "Tab"
mods = "Control|Shift"

# Super+w -> Close window (Ctrl+b w)
[[keyboard.bindings]]
chars = "\u0002W"
key = "w"
mods = "Super"

# Super+PageDown -> Next Pane (Ctrl+b o)
[[keyboard.bindings]]
chars = "\u0002o"
key = "PageDown"
mods = "Super"

# Control+Shift+D / Super+Shift+D -> Split Pane Horizontally (Ctrl+b ")
[[keyboard.bindings]]
chars = "\u0002\""
key = "D"
mods = "Control|Shift"
[[keyboard.bindings]]
chars = "\u0002\""
key = "D"
mods = "Super|Shift"

# Control+Shift+Alt+D -> Split Pane Vertically (Ctrl+b %)
[[keyboard.bindings]]
chars = "\u0002%"
key = "D"
mods = "Control|Shift|Alt"
[[keyboard.bindings]]
chars = "\u0002%"
key = "D"
mods = "Super|Shift|Alt"

# Control+Shift+Enter / Super+Shift+Enter -> Zoom Pane (Ctrl+b z)
[[keyboard.bindings]]
chars = "\u0002z"
key = "Return"
mods = "Control|Shift"
[[keyboard.bindings]]
chars = "\u0002z"
key = "Return"
mods = "Super|Shift"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 100000

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
dynamic_padding = true
dynamic_title = true

[window.dimensions]
columns = 95
lines = 34

[window.position]
x = 2890
y = 0
