import = ["/Users/keith/.cache/wal/colors-alacritty.yml"]

[cursor]
style = "Block"
thickness = 0.1
unfocused_hollow = true

[font]
size = 13

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
#family = "Monaspace Neon"
family = "MonaspiceNe NFP"
style = "Light"

[[keyboard.bindings]]
chars = "\bK"
key = "K"
mods = "Super"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Super|Shift"

# Tmux
[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Super"

[[keyboard.bindings]]
chars = "\u0002n"
key = "}"
mods = "Super|Shift"

[[keyboard.bindings]]
chars = "\u0002p"
key = "{"
mods = "Super|Shift"

[[keyboard.bindings]]
chars = "\u0002W"
key = "w"
mods = "Super"

[[keyboard.bindings]]
chars = "\u0002n"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002p"
key = "Tab"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0002o"
key = "PageDown"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002\""
key = "D"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u0002%"
key = "D"
mods = "Control|Shift|Alt"

[[keyboard.bindings]]
chars = "\u0002z"
key = "Return"
mods = "Control|Shift"

# - { key: D, mods: Command, chars: "\x06\x76" }
# - { key: D, mods: Command|Shift, chars: "\x06\x73" }
# - { key: W, mods: Command, chars: "\x06\x78" }
# - { key: H, mods: Command, chars: "\x06\x68" }
# - { key: J, mods: Command, chars: "\x06\x6a" }
# - { key: K, mods: Command, chars: "\x06\x6b" }
# - { key: L, mods: Command, chars: "\x06\x6c" }
# - { key: T, mods: Command, chars: "\x06\x63" }
# - { key: Key1, mods: Command, chars: "\x06\x31" }
# - { key: Key2, mods: Command, chars: "\x06\x32" }
# - { key: Key3, mods: Command, chars: "\x06\x33" }
# - { key: Key4, mods: Command, chars: "\x06\x34" }
# - { key: Key5, mods: Command, chars: "\x06\x35" }
# - { key: Key6, mods: Command, chars: "\x06\x36" }
# - { key: Key7, mods: Command, chars: "\x06\x37" }
# - { key: Key8, mods: Command, chars: "\x06\x38" }
# - { key: Key9, mods: Command, chars: "\x06\x39" }
# - { key: Left, mods: Command, chars: "\x06\x48" }
# - { key: Down, mods: Command, chars: "\x06\x4a" }
# - { key: Up, mods: Command, chars: "\x06\x4b" }
# - { key: Right, mods: Command, chars: "\x06\x4c" }

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 100000

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
dynamic_padding = true
dynamic_title = true

[window.dimensions]
columns = 95
lines = 34

[window.position]
x = 2890
y = 0
